#
#  Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       Fraunhofer IEE - initial API and implementation
#
#

install:
  postgres: true
  vault: true

participantId: did:web:dataspcae:issuer
namespaceOverride: ""

issuer:
  image:
    repository: ghcr.io/re4de/dataspace-issuer
    tag: 1.1.0-edc0.14.0
  scheduling:
    label: null
  endpoints:
    default:
      path: /api
      port: 8080
      public: false
    identity:
      path: /api/identity
      port: 8082
      public: false
    sts:
      path: /api/sts
      port: 8083
      public: false
    version:
      path: /api/version
      port: 8084
      public: true
    did:
      path: /
      port: 8085
      public: true
    issuance:
      path: /api/issuance
      port: 8086
      public: true
    admin:
      path: /api/admin
      port: 8087
      public: false
    statuslist:
      path: /api/statuslist
      port: 8090
      public: true
  service:
    enabled: true
  ingress:
    enabled: true
    className: nginx
    host: changeme
    tls:
      enabled: false
      issuer: cert-issuer
  startupProbe:
    enabled: true
    initialDelaySeconds: 1
    periodSeconds: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 1
    periodSeconds: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 3
    periodSeconds: 5
  edc:
    core:
      retriesMax: 5
      backoffMin: 500
      backoffMax: 10000
      logOnRetry: false
      logOnRetryScheduled: false
      logOnRetriesExceeded: false
      logOnRetryFailedAttempt: false
      logOnRetryAbort: false
    http:
      clientHttpsEnforce: false
      clientTimeoutConnect: 30
      clientTimeoutRead: 30
      clientSendBuffer: 0
      clientReceiveBuffer: 0
    vault:
      healthCheck: true
      healthCheckStandBy: false
      healthCheckPath: /v1/sys/health
      tokenScheduledRenew: true
      tokenTTL: 300
      tokenRenewBuffer: 30
      secretPath: /v1/secret
    sql:
      fetchSize: 5000
    issuer:
      statuslist:
        signingKeyAlias: statuslist-signing-key
      iam:
        didWebHttps: true
      seed:
        superUserKey: c3VwZXItdXNlcg==.changeme

vault:
  image:
    repository: hashicorp/vault
    tag: 1.18.1
  dev:
    devRootToken: changeme
  persistence:
    size: 8Gi
    volumeName: vault-vol
    storageClass: changeme

postgres:
  persistence:
    storageClass: changeme
  auth:
    existingSecret: postgres-secret
  customUser:
    name: edc
    database: edc
    existingSecret: postgres-secret
    secretKeys:
      name: null
      database: null
      password: password
  initdb:
    scriptsConfigMap: postgres
