{{/*
Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)

This program and the accompanying materials are made available under the
terms of the Apache License, Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0

SPDX-License-Identifier: Apache-2.0

Contributors:
     Fraunhofer IEE - initial API and implementation
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "issuer.labels" . | nindent 4 }}
data:
  init-membership-attestation.sql: |
    \c {{ .Values.postgres.customUser.database }} {{ .Values.postgres.customUser.name }}
    CREATE TABLE IF NOT EXISTS membership_attestations
    (
        holder_id   varchar                                 not null,
        id          varchar     default gen_random_uuid()   not null
            constraint attestations_pk
                primary key
        );

    CREATE UNIQUE INDEX IF NOT EXISTS membership_attestation_holder_id_uindex
        ON membership_attestations (holder_id);
  init-marketPartner-attestation.sql: |
    \c {{ .Values.postgres.customUser.database }} {{ .Values.postgres.customUser.name }}
    CREATE TABLE IF NOT EXISTS marketpartner_attestations
    (
        company_name        varchar                                 not null,
        company_uid         varchar                                 not null,
        sector              varchar     default 'electricity'       not null,
        code_issuing_body   varchar     default 'BDEW'              not null,
        market_role         json                                    not null,
        holder_id           varchar                                 not null,
        id                  varchar     default gen_random_uuid()   not null
            constraint markt_attestations_pk
                primary key
    );

    CREATE UNIQUE INDEX IF NOT EXISTS marketpartner_attestation_holder_id_uindex
        ON marketpartner_attestations (holder_id);