{{/*
Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)

This program and the accompanying materials are made available under the
terms of the Apache License, Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0

SPDX-License-Identifier: Apache-2.0

Contributors:
     Fraunhofer IEE - initial API and implementation
*/}}

{{- if .Values.postgres.auth.existingSecret }}
{{- $secret := lookup "v1" "Secret" (include "common.namespace" .) .Values.postgres.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.auth.existingSecret }}
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "issuer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if or (not $secret) (not $secret.data) (not (index $secret.data .Values.postgres.auth.secretKeys.adminPasswordKey)) }}
  {{ .Values.postgres.auth.secretKeys.adminPasswordKey }}: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  {{ .Values.postgres.auth.secretKeys.adminPasswordKey }}: {{ index $secret.data .Values.postgres.auth.secretKeys.adminPasswordKey }}
  {{- end }}
  {{- if or (not $secret) (not $secret.data) (not (index $secret.data .Values.postgres.customUser.secretKeys.password)) }}
  {{ .Values.postgres.customUser.secretKeys.password }}: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  {{ .Values.postgres.customUser.secretKeys.password }}: {{ index $secret.data .Values.postgres.customUser.secretKeys.password }}
  {{- end }}
{{- end }}