{{/*
Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)

This program and the accompanying materials are made available under the
terms of the Apache License, Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0

SPDX-License-Identifier: Apache-2.0

Contributors:
     Fraunhofer IEE - initial API and implementation
*/}}

{{- if .Values.issuer.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: issuer
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "issuer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{- include "issuer.matchLabels" . | nindent 4 }}
  ports:
    {{- range $k, $v := .Values.issuer.endpoints }}
    - name: {{ $k }}
      port: {{ $v.port }}
      targetPort: {{ $v.port }}
      protocol: TCP
    {{- end }}
  {{- end }}