{{- if .Values.postgresql.auth.existingSecret }}
{{- $secret := lookup "v1" "Secret" (include "common.namespace" .) .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "issuer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if or (not $secret) (not $secret.data) (not (index $secret.data .Values.postgresql.auth.secretKeys.adminPasswordKey)) }}
  {{ .Values.postgresql.auth.secretKeys.adminPasswordKey }}: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  {{ .Values.postgresql.auth.secretKeys.adminPasswordKey }}: {{ index $secret.data .Values.postgresql.auth.secretKeys.adminPasswordKey }}
  {{- end }}
  {{- if or (not $secret) (not $secret.data) (not (index $secret.data .Values.postgresql.auth.secretKeys.userPasswordKey)) }}
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ index $secret.data .Values.postgresql.auth.secretKeys.userPasswordKey }}
  {{- end }}
  {{- if or (not $secret) (not $secret.data) (not (index $secret.data .Values.postgresql.auth.secretKeys.replicationPasswordKey)) }}
  {{ .Values.postgresql.auth.secretKeys.replicationPasswordKey }}: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  {{ .Values.postgresql.auth.secretKeys.replicationPasswordKey }}: {{ index $secret.data .Values.postgresql.auth.secretKeys.replicationPasswordKey }}
  {{- end }}
{{- end }}