edc.participant.id=did:web:localhost%3A20085:issuer
edc.component.id=issuer
edc.hostname=localhost

edc.iam.did.web.use.https=false

edc.issuer.api.superuser.key=c3VwZXItdXNlcg==.devpass
edc.issuer.did=did:web:localhost%3A20085:issuer
edc.issuer.base.url=http://localhost:20086
edc.issuer.statuslist.signing.key.alias=statuslist-signing-key

web.http.path=/api
web.http.port=20080
web.http.identity.path=/api/identity
web.http.identity.port=20082
web.http.sts.path=/api/sts
web.http.sts.port=20083
web.http.version.path=/api/version
web.http.version.port=20084
web.http.did.path=/
web.http.did.port=20085
web.http.issuance.path=/api/issuance
web.http.issuance.port=20086
web.http.issueradmin.path=/api/admin
web.http.issueradmin.port=20087
web.http.statuslist.path=/api/statuslist
web.http.statuslist.port=20090

edc.vault.hashicorp.url=http://localhost:8200
edc.vault.hashicorp.token=devpass

edc.sql.schema.autocreate=true
edc.datasource.default.user=edc
edc.datasource.default.password=devpass
edc.datasource.default.url=jdbc:postgresql://localhost:5433/edc