name: "Helm Chart Build and Publish"

on:
  workflow_dispatch:

env:
  REPOSITORY: ghcr.io/re4de

jobs:
  Helm:
    name: "Build and Publish Release Helm Chart"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Helm Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Helm Package
        run: |
          helm dependency update ./chart
          helm package ./chart
      - name: Helm Publish
        run: helm push ./*.tgz oci://$REPOSITORY/charts